export enum EventType {
    NOTE_OFF = 0x8,
    NOTE_ON = 0x9,
    NOTE_AFTERTOUCH = 0xa,
    CONTROLLER = 0xb,
    PROGRAM_CHANGE = 0xc,
    CHANNEL_AFTERTOUCH = 0xd,
    PITCH_BEND_EVENT = 0xe,
    SYSTEM_EXCLUSIVE_EVENT = 0xf,
    META_EVENT_TYPE = 0xff,
    END_OF_FILE = -1,
}

export enum MetaEventType {
    TEXT_EVENT = 0x01,
    COPYRIGHT_NOTICE = 0x02,
    TRACK_NAME = 0x03,
    INSTRUMENT_NAME = 0x04,
    LYRICS = 0x05,
    MARKER = 0x06,
    CUE_POINT = 0x07,
    MIDI_CHANNEL_PREFIX = 0x20,
    MIDI_PORT = 0x21,
    END_OF_TRACK = 0x2f,
    SET_TEMPO = 0x51,
    SMPTE_OFFSET = 0x54,
    TIME_SIGNATURE = 0x58,
    KEY_SIGNATURE = 0x59,
    END_OF_FILE = -1,
}
